### ISSUE TITLE
CDN URL is missing protocol in JS pub/sub tutorial

### ISSUE THREAD

**Issue by Srushtika** [ably/tutorials#46]
The CDN URL is missing protocol information in the code sample on the website. (not the GitHub example)

See code for step 2: https://www.ably.io/tutorials/publish-subscribe#lang-javascript

**Comment by SimonWoolf** [comment]
It's a [protocol-relative url](https://en.m.wikipedia.org/wiki/URL#Protocol-relative_URLs)

**Comment by Srushtika** [comment]
Understood! However - when i'm using it in the code, it is automatically using  file://cdn.ably.io/lib/ably.min-1.js and hence showing an error on the console.
How to prevent this? @SimonWoolf

**Comment by SimonWoolf** [comment]
Ah, good point. That's presumably because you're developing with an html file open directly in a browser, not through a Web server, so the 'current protocol' is just file://. We should change that to https then, to allow than usecase - no point forcing everyone to use a local web server. 

Could you do a pr with that change, in this tutorial and any others that need the same fix?

**Comment by Srushtika** [comment]
Ah, ok. Understood!
Sure, I'll raise a PR @SimonWoolf ! Thanks.

**Comment by Srushtika** [comment]
Closing this as fixed directly in master, [here](https://github.com/ably/docs/commit/c745e5f78765b9fa7498bb7944716e916550c944)
